### ISSUE TITLE
Any way to tell if something you submitted was approved and/or where to find it?

### ISSUE THREAD

**Issue by tpmeredith** [MicrosoftDocs/flow-docs#10]
Is there any place to check that?

@sunaysv and @mgblythe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf8d0d2-3a6f-c3f1-494d-b0ea73c22f9b
* Version Independent ID: 41bc35b2-5a4d-7406-1ae7-27b292033fcd
* Content: [Submit a flow template - Microsoft Flow](https://docs.microsoft.com/en-us/flow/publish-a-template)
* Content Source: [flow-docs/publish-a-template.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/publish-a-template.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by MSFTMan** [comment]
@tpmeredith Thanks for your question. You can check the status of approval requests from within Microsoft Flow. Sign in -> select **Approvals** -> select **History**. You'll see the status of each request under the **Status** column.
