### ISSUE TITLE
Issue using Adaptive Card with MS Teams connector

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/flow-docs#100]
Couldn't figure out a better place to leave this feedback. Could someone look at: https://stackoverflow.com/questions/55070910/microsoft-flow-teams-adaptive-card

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf98fbf-59fc-825d-e8bc-b4b5b42719a2
* Version Independent ID: 22977ae9-2f4b-c98e-d19d-1d8ebf43fbd2
* Content: [Get started - Microsoft Flow](https://docs.microsoft.com/en-us/flow/getting-started)
* Content Source: [flow-docs/getting-started.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/getting-started.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@clearab Thanks for reporting this issue. This issue was resolved in the StackOverflow post, so I'll close it here. Thanks!

**Comment by bkt7878** [comment]
scanpick
