### ISSUE TITLE
Limit of 17 approvers undocumented

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/flow-docs#105]
An approval flow fails with more than 17 approvers and gives the following message:

The request failed. Error code: 'ApprovalAssignedToTooManyUsers'. Error Message: 'The approval may not be assigned to more than 17 users.'.

I can't find any information about this limit anywhere, but searches keep bringing me to this page, so it seems like a reasonable place to document it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Microsoft Flow](https://docs.microsoft.com/en-us/flow/limits-and-config)
* Content Source: [flow-docs/limits-and-config.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@FISHMANPET Thanks for using Microsoft Flow. To get around this limitation, you just need to upgrade your CDS database. Thanks!

**Comment by FISHMANPET** [comment]
This is an error we received in Microsoft Flow, not a Powerapp.  The Flow itself only uses the Approvals connection and a Gmail connection, so as far as I can tell there's no Common Data Service database to upgrade.

I realize this isn't a venue for support, but all the documentation I can find on "CDS" refers to something used in PowerApps but not Flow (it refers to flows using PowerApps but I'm specifically talking about the Microsoft Flow product) so there's a documentation gap somewhere.
