### ISSUE TITLE
Multiple, overlapping, inconsistent pages - please consolidate Gateway information 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/flow-docs#106]
Please integrate, consolidate or cross-reference all of the content about Data Gateways. There are currently page at https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/gateway-management and https://docs.microsoft.com/en-us/power-bi/service-gateway-getting-started. They are similar but different, since the data gateways are shared between Power BI, PowerApps and Flow, the documentation should be shared also. There is different good stuff in all 3 locations, but some inconsistencies in format and topics make it much harder than necessary to get a thorough understanding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 213d2c56-a05d-0ba5-6165-f52e0eb1be7b
* Version Independent ID: b089a13e-14f0-116c-fcef-474760ee6068
* Content: [Learn to manage on-premises data gateways - Microsoft Flow](https://docs.microsoft.com/en-us/flow/gateway-manage#install-a-gateway)
* Content Source: [flow-docs/gateway-manage.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/gateway-manage.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@DeanGross Thanks for your feedback. I've discussed with the team and they are actively working to address this issue for gateways and other services as well.
