### ISSUE TITLE
EUROPE IP Range incorrect

### ISSUE THREAD

**Issue by AlexRademeyer** [MicrosoftDocs/flow-docs#107]
The IP ranges above are incorrect.
I have a flow posting HTTP requests in a European region.
The IP it is posting from is 23.97.218.130 and this is not in the "Europe" range above.
However it IS in the Azure Logic Apps equivalent document......
https://docs.microsoft.com/bs-latn-ba/azure/logic-apps/logic-apps-limits-and-config?view=azurenotificationhubs-1.0.7
This caused a lot of frustration because 1 of my assumptions was that the IP range above would be correct so I did not think to check it......
Would appreciate if this was corrected OR if I have misunderstood, if it could be clarified in the doc.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Microsoft Flow](https://docs.microsoft.com/en-gb/flow/limits-and-config#feedback)
* Content Source: [flow-docs/limits-and-config.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by BrianZhangLarsen** [comment]
I have the same problem - IP Range being incorrect. My flow is posting from "40.68.222.65", but the listed all starts with 40.69.?.? 

It is quite important that this documentation is correct.

**Comment by MSFTMan** [comment]
@AlexRademeyer and @BrianZhangLarsen Flows can make calls from Logic apps as well. These additional ip addresses are called out in the logic apps documentation. There is a link to the Logic apps content in this Microsoft Flow document. However, to highlight it, I've added an **Important** highlight in this document. Thanks!

**Comment by joelhellman** [comment]
@MSFTMan I experienced the same issue today. I think you added a very helpful clarification to the article https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-limits-and-config?tabs=azure-portal#firewall-configuration-ip-addresses-and-service-tags 

> Note
> If you're using [Power Automate](https://docs.microsoft.com/en-us/power-automate/getting-started), some actions, such as HTTP and HTTP + OpenAPI, go directly through the Azure Logic Apps service and come from the IP addresses that are listed here. For more information about the IP addresses used by Power Automate, see [Limits and configuration for Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config#ip-address-configuration).
> 

but I'd expected that information in the main article about outbound ip addresses for the power platform, and I never found it, instead I found this issue. Could we add the notice on this page as well?:
https://docs.microsoft.com/en-us/connectors/common/outbound-ip-addresses#power-platform
