### ISSUE TITLE
Delay in Add a SharePoint list or library as owner

### ISSUE THREAD

**Issue by zshane15** [MicrosoftDocs/flow-docs#108]
How long does it take for a list/library to appear in the drop-down for Owners &gt; SharePoint. I'm trying to add a newly created Document Library and it still has not appeared after about 30 mins. I've cleared my cache, logged in/out and it still does not appear in the drop-down. Does the list/library need to be indexed first (i.e. +/- 24hrs later?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to add other owners to a flow and create team flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-team-flows#feedback)
* Content Source: [flow-docs/create-team-flows.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@zshane15 Thanks for using Microsoft Flow. I tried creating a team site and within a few minutes I was able to add it as an owner in Microsoft Flow. Please let us know if you are still seeing a problem. - Deon
