### ISSUE TITLE
Query regarding execution of Flow

### ISSUE THREAD

**Issue by jsvictor** [MicrosoftDocs/flow-docs#109]
Hi,

I would like to create a flow, in which I am sent an email notification whenever an RSS feed is published at a server. I see that RSS feed can be created by providing the URL of RSS feed server, and selecting keywords (https://flow.microsoft.com/en-us/galleries/public/templates/5ccc3740296211e6b75bc95bc07ea764/send-news-feed-to-email-based-on-a-condition/ ). But I would like to know if the periodic lookup for new feed (that is, to check if new item has been published) will be executed at my browser/ app, or in Cloud, at Microsoft Flow servers. I would not like to bog down my browser/ mobile with a large number of periodic poling requests, in case I create multiple such flows for different servers of the technology of my interest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee8a6fc-8a07-bcf7-412f-21344c46f4c6
* Version Independent ID: 3289c7dd-3a4a-0d96-0e4c-e08689ab2c2d
* Content: [Frequently asked questions - Microsoft Flow](https://docs.microsoft.com/en-us/flow/frequently-asked-questions#feedback)
* Content Source: [flow-docs/frequently-asked-questions.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/frequently-asked-questions.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@jsvictor Thanks for using Microsoft Flow. All flow run in the cloud. When flows run, there is no impact to your device.

Thanks,
Deon

**Comment by frippe75** [comment]
Is this really true? I have a flow monitoring a SharePoint folder for added documents and uploads these files to Azure resources for processing using Automation Runbooks. If I block my laptop IP from reaching the Azure resources the flow will fail (i.e the actual flow seems to be dependenant on running on my laptop. I was hoping to see SharePoint IP addresses trying to reach my Azure storage account. But it's actually my laptop. So how is the flow running  in the cloud???
