### ISSUE TITLE
out of date release notes

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/flow-docs#11]
these notes have not been updated in almost 3 months. There have been many announcements made in Product Updates blog. Please update this page to document the changes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53c02fee-38c5-649a-0faa-23bf5edbcd7f
* Version Independent ID: 65ee90be-a0f2-15c0-b487-7210eddda17a
* Content: [Release notes - Microsoft Flow](https://docs.microsoft.com/en-us/flow/release-notes)
* Content Source: [flow-docs/release-notes.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/release-notes.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@DeanGross  Thanks for reporting this issue. We've updated the release notes: https://docs.microsoft.com/en-us/flow/release-notes

**Comment by DeanGross** [comment]
Thanks, but these notes are still out of date, there were many announcements in September which are note included.
