### ISSUE TITLE
Unable to get Organization ID in MS Flow

### ISSUE THREAD

**Issue by samikroy** [MicrosoftDocs/flow-docs#110]
Unable to get Organization ID as mentioned in the article. Below is the screenshot.
![image](https://user-images.githubusercontent.com/20562985/56381447-80c82d00-6232-11e9-9dea-89e0c4138b68.png)

![image](https://user-images.githubusercontent.com/20562985/56381544-d43a7b00-6232-11e9-9ed1-70bdf4ca3310.png)

Masked areas are Environment names.
It is a paid tenant.

**Comment by MSFTMan** [comment]
@samikroy Thanks for using Microsoft flow. 

The Organization ID is a unique name for the environment that stores your flows. You can see the Organization ID in the environment switcher at the top-right of Microsoft Flow. Note that the Organization ID is different from the Environment ID (which is the GUID that appears in the URL of the flow). See more details here: https://docs.microsoft.com/en-us/flow/web-api#compose-http-requests 

Thanks,
Deon
