### ISSUE TITLE
How to use IBM DB2 connector for multiple users ?

### ISSUE THREAD

**Issue by rohitblue28** [MicrosoftDocs/flow-docs#112]
I have requirement to connect to a IBM DB2 system in clients environment and fetch data.

This needs to work on the fly when a user clicks a button system should pull the information IBM DB2 tables.

Do i need licenses for all the users who will be using this flow ?

Since all the users will be using the Flow to connect to DB2 where should i install the gateway ?

**Comment by MSFTMan** [comment]
@schabungbam Please take a look at this customer question about connectors.

**Comment by rohitblue28** [comment]
@schabungbam - Kindly help understand this.

**Comment by MSFTMan** [comment]
@schabungbam  please take a look.

**Comment by MSFTMan** [comment]
@rohitblue28 Thanks for raising this question. This sounds like a licensing question. Please raise this issue on the connectors forums here: https://powerusers.microsoft.com/t5/Connecting-To-Data/bd-p/ConnectingToData

Thanks,
Deon
