### ISSUE TITLE
"Submit as template" is not there as one of the option

### ISSUE THREAD

**Issue by vnarula** [MicrosoftDocs/flow-docs#113]
"Submit as template" is not there as one of the option, This issue was raised earlier as well and it was closed without fixing the issue , can  someone pls investigate and resolve appropriately or add more information ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf8d0d2-3a6f-c3f1-494d-b0ea73c22f9b
* Version Independent ID: 41bc35b2-5a4d-7406-1ae7-27b292033fcd
* Content: [Submit a flow template - Microsoft Flow](https://docs.microsoft.com/en-us/flow/publish-a-template#feedback)
* Content Source: [flow-docs/publish-a-template.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/publish-a-template.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by MSFTMan** [comment]
@vnarula Thanks for reporting this issue. I just checked one of my flows and I see the "Submit as template" option. But, it's only showing on the **More** menu when I go into the details for the flow. (It doesn't show from the My flows page). 

Also, your flow must have run successfully at least once before you can submit as a template. Please let me know. Thanks!

**Comment by MSFTMan** [comment]
@vnarula Thanks again for using Microsoft Flow. We have not heard back from you so we are closing this issue. Kindly let us know if you need any other assistance. -Deon
