### ISSUE TITLE
Can't find this template anymore

### ISSUE THREAD

**Issue by timp3261** [MicrosoftDocs/flow-docs#114]
as title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f7b3337-c547-4960-fa13-ca16a559b083
* Version Independent ID: 9b02414f-872e-14da-71c6-bd68fbb0e23e
* Content: [Common Data Service - Microsoft Flow](https://docs.microsoft.com/en-us/flow/common-data-model-intro)
* Content Source: [flow-docs/common-data-model-intro.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/common-data-model-intro.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@timp3261 Thanks for using Microsoft Flow and for letting us know the template is missing. We'll look into the missing template. You can use any other Common Data Service template that the search results return.. The one shown in the docs is just an example. Thanks!
