### ISSUE TITLE
How can I terminate the approval

### ISSUE THREAD

**Issue by mixor007** [MicrosoftDocs/flow-docs#115]
So great of parallel approval flow!
If any rejection from direct manager, HR manager or Sales team manager is decide, can I terminate the flow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0b55bf7-5493-bcb9-8689-8658ead17676
* Version Independent ID: 34d682d0-2283-3b1a-2453-6d7dbc26e5a8
* Content: [Create a parallel modern approval workflow - Microsoft Flow](https://docs.microsoft.com/en-us/flow/parallel-modern-approvals#feedback)
* Content Source: [flow-docs/parallel-modern-approvals.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/parallel-modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@mixor007 Thanks for using Microsoft Flow. Yes, you can terminate the flow at any time. To terminate, you just don't add any other actions after the rejection.
