### ISSUE TITLE
Sharing Flow ownership forces shared user to create new connection

### ISSUE THREAD

**Issue by JoeAFS** [MicrosoftDocs/flow-docs#116]
When I give someone ownership of a Flow that I created which contains a Plumsail Action (i'm not 100% if PS is the culprit or if this is normal behavior), it makes them create their own connection to PS. this is not feasible since it will then not run for anyone else until they edit the flow with their connection.  Is this normal? Should each person I make an owner be required to create their own connection like that?

**Comment by MSFTMan** [comment]
@JoeAFS  Thanks for reporting this issue. I've made the engineering team aware of this issue. While they work on a fix, you can workaround the issue by directly sharing the **connection** with the person whom you made an owner of the flow.  Thanks!
