### ISSUE TITLE
No Recent Updates

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/flow-docs#117]
This page has not been updated in many months. Please update it with the release notes more frequently

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53c02fee-38c5-649a-0faa-23bf5edbcd7f
* Version Independent ID: 65ee90be-a0f2-15c0-b487-7210eddda17a
* Content: [Release notes - Microsoft Flow](https://docs.microsoft.com/en-us/flow/release-notes)
* Content Source: [flow-docs/release-notes.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/release-notes.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
Hi @DeanGross Thanks for using Microsoft Flow. You can find the most recent release notes here: https://docs.microsoft.com/en-us/business-applications-release-notes/ 

Thanks!

**Comment by DeanGross** [comment]
Thanks, it would be helpful if this page contained a link to that location.

**Comment by GiantCrocodile** [comment]
Just posted the same feedback as yours @DeanGross via the 'Is this page helpful' feedback function. No clue why this is not properly updated/changed.
