### ISSUE TITLE
Just a Few Typos

### ISSUE THREAD

**Issue by tu-n-tran** [MicrosoftDocs/flow-docs#118]
Just some very minor corrections you may want to be aware of:

if someone attemps to approve a timed-out request...
*attempts

Minimum postone interval
*believe you meant postpone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Microsoft Flow](https://docs.microsoft.com/en-us/flow/limits-and-config#feedback)
* Content Source: [flow-docs/limits-and-config.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@tu-n-tran Thanks for reporting these issues. I've fixed them and posted the fixes, so you should see the fixes soon.
