### ISSUE TITLE
What data is made anonymous? 

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/flow-docs#119]
It is unclear to me what data will remain, and what will be removed before the Flow is made into a template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf8d0d2-3a6f-c3f1-494d-b0ea73c22f9b
* Version Independent ID: 41bc35b2-5a4d-7406-1ae7-27b292033fcd
* Content: [Submit a flow template - Microsoft Flow](https://docs.microsoft.com/en-us/flow/publish-a-template)
* Content Source: [flow-docs/publish-a-template.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/publish-a-template.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by MSFTMan** [comment]
@clearab Thanks for asking. I've contacted the team about this and will let you know what I learn about this issue. Thanks!

**Comment by MSFTMan** [comment]
@clearab We essentially remove all data from your flows before they are published as templates. Thank you.
