### ISSUE TITLE
Microsoft flow

### ISSUE THREAD

**Issue by Jstiles3** [MicrosoftDocs/flow-docs#12]
It been awhile do you think it will work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25f8411c-d9d8-54c8-cfb9-bafe3856d061
* Version Independent ID: 5bd1ee67-4ca2-a0d7-60e8-0ed39835bc4b
* Content: [Understand on-premises data gateways - Microsoft Flow](https://docs.microsoft.com/en-us/flow/gateway-reference)
* Content Source: [flow-docs/gateway-reference.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/gateway-reference.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@Jstiles3 Thanks for using Microsoft Flow. So I can help you better, please let me know what you are curious about. - Deon

**Comment by MSFTMan** [comment]
@Jstiles3 Thanks again for using Microsoft Flow. We haven't heard from you in a while regarding our clarification question, so I'll close this issue. Don't hesitate to contact us again if you need anything at all.
