### ISSUE TITLE
Appreciate it and wish to approval buttons.

### ISSUE THREAD

**Issue by PeterWxin** [MicrosoftDocs/flow-docs#120]
Very helpful. Thanks a lot!
Wish to figure out how to make Approve, Reject and Submit buttons work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da15c461-b88d-7497-cd59-efcd785d5994
* Version Independent ID: 00dd913a-44c7-b407-02c5-528c3b0e7643
* Content: [Learn to create flows that post adaptive cards to Microsoft Teams - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-adaptive-cards-teams#feedback)
* Content Source: [flow-docs/create-adaptive-cards-teams.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-adaptive-cards-teams.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@PeterWxin Hi Peter, thanks for using Microsoft Flow. Use this document to learn about creating custom response options/buttons: https://docs.microsoft.com/en-us/flow/create-approval-response-options 

Thanks,
Deon
