### ISSUE TITLE
Cancel a running flow from a REST api?

### ISSUE THREAD

**Issue by benwinding** [MicrosoftDocs/flow-docs#123]
Hi Guys,

Love the Microsoft Flow application and the docs you've made are pretty good, just wondering if it is possible to _cancel_ a running flow from a REST api? As in 

1. Trigger on Request
2. Cancel Flow > name_id, running_id

We want to trigger flows, store their reference information and cancel them if we need to. We found these resources, but are unable to workout how to use them easily.
https://docs.microsoft.com/en-us/rest/api/logic/workflowruns/cancel

Cheers,
Ben

**Comment by MSFTMan** [comment]
@benwinding Thanks for using Microsoft Flow. I'll look into this and get back to you.

**Comment by MSFTMan** [comment]
@benwinding Thanks for using Microsoft Flow. At this time, we do not provide a way to cancel a running flow programatically. You might consider using logic apps as a workaround. Thanks!

**Comment by benwinding** [comment]
Thanks for checking that out @MSFTMan,
A real shame, that's one of the most important features we want for _long-running flows_ is to terminate them. Hope this get's incorporated in the future,
Cheers,
Ben
