### ISSUE TITLE
Unclear licensing requirements

### ISSUE THREAD

**Issue by wnzn** [MicrosoftDocs/flow-docs#124]
The article states: "A Microsoft Flow account with a Plan 2 license (Plan 2 is needed to use premium features. Approvals is a premium feature.)"

However, from the Flow pricing page, it appears you only need a Plan 1 license to use premium connectors.
Https://flow.microsoft.com/en-us/pricing/?currency=EUR

So which one is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b2c12c-7262-de3d-eb95-410fb6a33df6
* Version Independent ID: b316d8da-19ac-6b00-7675-2b9d03d33377
* Content: [Create approval flows with custom responses - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-approval-response-options#feedback)
* Content Source: [flow-docs/create-approval-response-options.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-approval-response-options.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@wnzn Thanks for reporting this issue. Plan 1 is needed for premium connectors. I've updated the doc.
