### ISSUE TITLE
i like this

### ISSUE THREAD

**Issue by adebayoyeleye** [MicrosoftDocs/flow-docs#13]
This guided learning is really awesome for bringing guys on board. cant wait to get to using documentation for advanced flows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb414721-8393-66f8-e39e-d41636068b3d
* Version Independent ID: 2bcf1a26-717a-294d-291f-366184a84457
* Content: [Get Started - Microsoft Flow](https://docs.microsoft.com/en-us/flow/guided-learning/get-started?tutorial-step=4)
* Content Source: [flow-docs/guided-learning/get-started.yml](https://github.com/MicrosoftDocs/flow-docs-pr/blob/live/flow-docs/guided-learning/get-started.yml)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@adebayoyeleye Thank you. We are happy you life GL. - deon
