### ISSUE TITLE
Approvals are not premium connectors

### ISSUE THREAD

**Issue by kylepdx** [MicrosoftDocs/flow-docs#134]
Within Flow when I view the connectors, Approval is NOT listed as a premium connector, but this document contradicts that.  Please clarify that only the Custom Approval option is premium.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b2c12c-7262-de3d-eb95-410fb6a33df6
* Version Independent ID: b316d8da-19ac-6b00-7675-2b9d03d33377
* Content: [Create approval flows with custom responses - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-approval-response-options#feedback)
* Content Source: [flow-docs/create-approval-response-options.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-approval-response-options.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@kylepdx I've updated the doc. Thanks for bringing this up.
