### ISSUE TITLE
still awesome

### ISSUE THREAD

**Issue by adebayoyeleye** [MicrosoftDocs/flow-docs#14]
we should be able to share this on social media so more people are aware of this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3757356-1078-e915-8998-2868858792c5
* Version Independent ID: 28cf37b6-6a21-9594-392d-29bef64912bb
* Content: [Build flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/guided-learning/build-flows?tutorial-step=8)
* Content Source: [flow-docs/guided-learning/build-flows.yml](https://github.com/MicrosoftDocs/flow-docs-pr/blob/live/flow-docs/guided-learning/build-flows.yml)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@adebayoyeleye  Thanks for using Microsoft Flow. I'll pass this suggestion on to the team. - Deon

**Comment by MSFTMan** [comment]
@JLevesque84 @stepsic-microsoft-com @KumarVivek FYI, customer loves GL so much, he want to share it on social media easily. I like the idea of have a Share button. Thoughts?

**Comment by MSFTMan** [comment]
@MargoC  Is there any plan to have a "Share" button on our Microsoft Learn content so that users can share the joy of Microsoft Learn via social media?

**Comment by MSFTMan** [comment]
@adebayoyeleye  Thanks for sharing your thoughts. We've begun moving much of our training material to Microsoft Learn (https://docs.microsoft.com/learn/). On Microsoft Learn, there's a "share" button at the end of each module. Per your feedback, the team is also considering adding a "share" button even before the end of the module.
