### ISSUE TITLE
Updating Credentials

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/flow-docs#15]
The instructions state that we should update the credentials if we delete a Flow owner but they don't state how to do this task. Please add this information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to add other owners to a flow and create team flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-team-flows)
* Content Source: [flow-docs/create-team-flows.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@DeanGross Thanks for using Microsoft Flow, and for reporting this issue. I'll take a look at it. - Deon

**Comment by MSFTMan** [comment]
@DeanGross I've added the steps to update the owner for a connection. Thank you for your patience.
