### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rbnswartz** [MicrosoftDocs/flow-docs#156]
Under the Microsoft Flow for enterprise developers section the Build Azure Functions link points to https://docs.microsoft.com/azure/azure-functions/functions-flow-scenario which doesn't exist anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e534fb-0608-62e2-e257-77ca64397af6
* Version Independent ID: 0f9e11dc-455d-e1cf-fbc1-89a07cb53ef6
* Content: [Microsoft Flow for enterprise developers, ISVs, and partners - Microsoft Flow](https://docs.microsoft.com/en-us/flow/developer/dev-enterprise-intro#feedback)
* Content Source: [flow-docs/developer/dev-enterprise-intro.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/developer/dev-enterprise-intro.md)
* Service: **flow**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by KumarVivek** [comment]
@rbnswartz The link is fixed now; thanks for the feedback.

Closing the issue.
