### ISSUE TITLE
Service Account Recommendations

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/flow-docs#16]
Please provide some guidance on the use of service accounts instead of user accounts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bf9b6c-5628-f18c-7027-45b21eb3b6bc
* Version Independent ID: a4394ad5-9d46-2a6d-16d9-48b0c88fb401
* Content: [Learn to connect to your data using connections and on-premises data gateways - Microsoft Flow](https://docs.microsoft.com/en-us/flow/add-manage-connections)
* Content Source: [flow-docs/add-manage-connections.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/add-manage-connections.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@DeanGross While you can log into Microsoft Flow with a service account and create flows, we don't recommend it in cases where the credentials for the service account are shared. - Deon

**Comment by MSFTMan** [comment]
@DeanGross  I've updated the faq regarding the use of service accounts: https://docs.microsoft.com/en-us/flow/frequently-asked-questions. 

Thank you for using Microsoft Flow.
