### ISSUE TITLE
Flow Approval Mark Down inconsistent

### ISSUE THREAD

**Issue by Yatinpurohit** [MicrosoftDocs/flow-docs#166]
The markdown table does not work in Outlook 2016. This is how it looks in Outlook 2016 -

\| Unit \| CP Test \|\|:------\|:----------\|\| Function \| IT \|\| Location \| Mumbai   \|\| Title   \| This is CP Flow Test \|\| CP   No. \| CP00001234 \|\| Amount   \| 2300000 \|
--

It works only in Outlook 365 Online.

**Comment by KumarVivek** [comment]
@Yatinpurohit Please report product-related issues in the Microsoft Flow support site: https://flow.microsoft.com/en-us/support/

Closing the issue.
