### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/flow-docs#17]
Please identify the prerequisites that must be met to create these types of Flows. I think that some type of Dynamics license is needed, but that is not stated and there may be some other requirements that must be met but i'm not sure what they are. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7759368-a61e-08ce-e24f-b43a200521dd
* Version Independent ID: 80c1d8d8-a995-1023-91f9-0a1fd687c5b6
* Content: [Create a business process flow in PowerApps - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-business-process-flow)
* Content Source: [flow-docs/create-business-process-flow.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-business-process-flow.md)
* Service: **crm-online**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by MSFTMan** [comment]
@DeanGross Thanks for sharing your thoughts. We'll look into this.

**Comment by MSFTMan** [comment]
@DeanGross I've updated the doc to show that that Flow Plan 2 is the prerequisite for creating business process flows. Thank you for using Microsoft Flow.
