### ISSUE TITLE
Separate Issues from Release Notes

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/flow-docs#18]
Please create a separate page for the issues and resolutions, those don't belong on the same page as the Release notes. 
Also, the number of release notes makes the page very long, it would be easier to use if the older notes, maybe before 2018, were put onto an Archive page to reduce the clutter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53c02fee-38c5-649a-0faa-23bf5edbcd7f
* Version Independent ID: 65ee90be-a0f2-15c0-b487-7210eddda17a
* Content: [Release notes - Microsoft Flow](https://docs.microsoft.com/en-us/flow/release-notes)
* Content Source: [flow-docs/release-notes.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/release-notes.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@DeanGross Thanks for sharing your thoughts. We are making some changes to this process and layout. You should see the results by late November.
