### ISSUE TITLE
Supported Browsers

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/flow-docs#19]
Is it really true that Internet Explorer and Firefox are not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee8a6fc-8a07-bcf7-412f-21344c46f4c6
* Version Independent ID: 3289c7dd-3a4a-0d96-0e4c-e08689ab2c2d
* Content: [Frequently asked questions - Microsoft Flow](https://docs.microsoft.com/en-us/flow/frequently-asked-questions)
* Content Source: [flow-docs/frequently-asked-questions.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/frequently-asked-questions.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@DeanGross Thanks for this question. We'v'e clarified our browser support here: https://docs.microsoft.com/flow/frequently-asked-questions#what-browsers-and-devices-can-i-use-with-microsoft-flow
