### ISSUE TITLE
Couple of queries regarding business process flow !

### ISSUE THREAD

**Issue by dips23** [MicrosoftDocs/flow-docs#20]
Hello,

Can you please help me in clarifying following details ?

1) How Business Process flow differs than traditional automated Microsoft flow template ?
2) Which Office 365 plan is requiring to create business process flow ?
3) Which environment is supported to create Business Process Flow ?

Thanks and Regards,
Dipti Chhatrapati

**Comment by MSFTMan** [comment]
@dips23 Thanks for your questions, and for your interest in business process flows (BPFs). 
1. BPFs allow you to create work flows that ensure consistent user input/behavior. Automated flows typically run without much user input after the flow is created.  Learn about BPFs here: https://docs.microsoft.com/en-us/flow/business-process-flows-overview
2. You need Microsoft Flow Plan 2 to create BPFs: https://preview.flow.microsoft.com/pricing/ 
3. Plan 2 allows you to create environment-specific policies.

**Comment by MSFTMan** [comment]
@dips23 Thanks for raising this issue. Do let us know if you have further questions.
