### ISSUE TITLE
Adding Owners

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/flow-docs#21]
When should we add a SP List/Library as owner instead of a Group? when should we add both? please provide some recommendations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to add other owners to a flow and create team flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-team-flows#create-a-team-flow)
* Content Source: [flow-docs/create-team-flows.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@DeanGross I've updated the document with our recommendation. Thank you for using Microsoft Flow.
