### ISSUE TITLE
option sets

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/flow-docs#22]
this page doesn't explain how to update an option set field

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f78faa65-bb08-e6bb-4b0e-6b1f3862b975
* Version Independent ID: 4efbfdaa-b753-1aae-7f09-ef97fe2f544d
* Content: [Create a flow with Dynamics 365 (online) - Microsoft Flow](https://docs.microsoft.com/en-us/flow/connection-dynamics365)
* Content Source: [flow-docs/connection-dynamics365.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/connection-dynamics365.md)
* Service: **flow**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by MSFTMan** [comment]
@JerryCRMI Thanks for your input. We'll update the content.

**Comment by MSFTMan** [comment]
@JerryCRMI thanks for reporting this issue. We are looking into it.

**Comment by MSFTMan** [comment]
@JerryCRMI Thanks for using Microsoft Flow. I've updated the content with option sets.
