### ISSUE TITLE
change tracking

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/flow-docs#23]
in the purple section up top you say change tracking is required. later you say it should be enabled. 

[IMPORTANT] In order for the flow to trigger on the Dynamics 365 entity, the entity definition should have Change Tracking enabled. See Enable change tracking to control data synchronization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f78faa65-bb08-e6bb-4b0e-6b1f3862b975
* Version Independent ID: 4efbfdaa-b753-1aae-7f09-ef97fe2f544d
* Content: [Create a flow with Dynamics 365 (online) - Microsoft Flow](https://docs.microsoft.com/en-us/flow/connection-dynamics365)
* Content Source: [flow-docs/connection-dynamics365.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/connection-dynamics365.md)
* Service: **flow**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by MSFTMan** [comment]
@JerryCRMI Thanks for pointing this out. I've updated the content to should that Change Tracking **must** be enabled: https://docs.microsoft.com/en-us/flow/connection-dynamics365
