### ISSUE TITLE
User Accounts that have MFA

### ISSUE THREAD

**Issue by roscocheeta** [MicrosoftDocs/flow-docs#24]
What's missing from this content is how to handle MFA / Aggressive timeout policies as this also affects Connectors for Flows that are using your credentials. I am always having to re-login to Connectors because of our MFA / login timeouts. There is mention of Service Accounts but the advice is to NOT use them. So how do we work around this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bf9b6c-5628-f18c-7027-45b21eb3b6bc
* Version Independent ID: a4394ad5-9d46-2a6d-16d9-48b0c88fb401
* Content: [Learn to connect to your data using connections and on-premises data gateways - Microsoft Flow](https://docs.microsoft.com/en-us/flow/add-manage-connections#troubleshoot-a-connection)
* Content Source: [flow-docs/add-manage-connections.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/add-manage-connections.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@roscocheeta  Thanks for your feedback. I'll follow up with the team and get back to you on this.

**Comment by roscocheeta** [comment]
Any updates on this @MSFTMan ?

**Comment by MSFTMan** [comment]
@roscocheeta Thanks for following up. I discussed with the team. Currently the timeout period for MFA and OAuth is 5 minutes. So we can help better, can you let us know: under what conditions are you encountering this timeout? Do you have specific steps we can try to reproduce this issue to understand it better?

**Comment by roscocheeta** [comment]
> @roscocheeta Thanks for following up. I discussed with the team. Currently the timeout period for MFA and OAuth is 5 minutes. So we can help better, can you let us know: under what conditions are you encountering this timeout? Do you have specific steps we can try to reproduce this issue to understand it better?

I observed this issue using a Flow that connects to Outlook and Forms. I observed every few weeks the Forms connector stops working and asks me "re-sign in" to re-authenticate that connector. 

I've also contacted my IT Department to see if they can look into it. I would note there are some forum posts on the Flows community forum about MFA affecting connectors. Some have found a workaround by whitelisting / trusting IP's for a particular user account, but don't think our Security team will allow that!

**Comment by MSFTMan** [comment]
> > @roscocheeta Thanks for following up. I discussed with the team. Currently the timeout period for MFA and OAuth is 5 minutes. So we can help better, can you let us know: under what conditions are you encountering this timeout? Do you have specific steps we can try to reproduce this issue to understand it better?
> 
> I observed this issue using a Flow that connects to Outlook and Forms. I observed every few weeks the Forms connector stops working and asks me "re-sign in" to re-authenticate that connector.
> 
> I've also contacted my IT Department to see if they can look into it. I would note there are some forum posts on the Flows community forum about MFA affecting connectors. Some have found a workaround by whitelisting / trusting IP's for a particular user account, but don't think our Security team will allow that!

Thanks @roscocheeta. I'll follow up with the team on this.

**Comment by LC-1** [comment]
I just wanted to comment to let you know I am having the same issue. We also have MFA, and to my knowledge, didn't change any of the "default" settings when we activated MFA. I look forward to hearing a solution to this issue outside of whitelisting IPs. This is especially true since it would require bumping to a higher subscription level in order to have the capability to whitelist.

**Comment by oberjc** [comment]
We were having the same problem and it was fixed by assigning the MaxAgeMultipfactor policy described in this document.
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes

New-AzureADPolicy -Definition @('{"TokenLifetimePolicy":{"Version":1,"MaxAgeMultiFactor":"until-revoked","MaxAgeSessionMultiFactor":"3.00:00:00"}}') -DisplayName "DefaultPolicyScenario" -IsOrganizationDefault $true -Type "TokenLifetimePolicy"

**Comment by MSFTMan** [comment]
@LC-1  @roscocheeta , does @oberjc solution work for you?

**Comment by MSFTMan** [comment]
> We were having the same problem and it was fixed by assigning the MaxAgeMultipfactor policy described in this document.
> https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes
> 
> New-AzureADPolicy -Definition @('{"TokenLifetimePolicy":{"Version":1,"MaxAgeMultiFactor":"until-revoked","MaxAgeSessionMultiFactor":"3.00:00:00"}}') -DisplayName "DefaultPolicyScenario" -IsOrganizationDefault $true -Type "TokenLifetimePolicy"

This is the recommended policy. Thank you.

**Comment by MSFTMan** [comment]
@roscocheeta Good news: This issue is now fixed so you should no longer see it. Thanks for using Microsoft Flow.
