### ISSUE TITLE
Correction to "not" expression description

### ISSUE THREAD

**Issue by spg-iwilson** [MicrosoftDocs/flow-docs#25]
In the table at the top of the page it has the following description for the "not" expression:

Takes two arguments and returns true if the arguments are false. 
Note: Both arguments must be Booleans.

This should be changed to something like:

Takes a boolean argument and returns the opposite value. e.g. if the argument is true, returns false, if the argument is false, returns true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27504e8c-568f-ee52-542c-5ca87c2906db
* Version Independent ID: dc8f9282-90ce-60e0-402c-ea8829b6334e
* Content: [Use expressions with conditions. - Microsoft Flow](https://docs.microsoft.com/en-us/flow/use-expressions-in-conditions)
* Content Source: [flow-docs/use-expressions-in-conditions.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/use-expressions-in-conditions.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@spg-iwilson Thanks for reporting this issue. It is now fixed in the document. The fix will be live in 10 minutes or less.
