### ISSUE TITLE
how do you specify multiple keywords in the subject filter?

### ISSUE THREAD

**Issue by mrlovat** [MicrosoftDocs/flow-docs#26]
how do you specify multiple keywords in the subject filter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38b2975-5eb6-1aa4-c1fd-d0f033ace5ca
* Version Independent ID: 85899731-9939-a779-29c4-4da652667b74
* Content: [Run flows based on email properties - Microsoft Flow](https://docs.microsoft.com/en-us/flow/email-triggers)
* Content Source: [flow-docs/email-triggers.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/email-triggers.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@mrlovat  You cannot use the subject filter to check multiple keywords. The subject filter works with a single specific string. To filter on multiple keywords, we recommend that you create a **condition**, use advanced mode of the condition, and use the "contains" statement to check for the keywords you care about. For example, you can check for something like this: contains 'lottery' or contains 'winner', etc.

**Comment by dNsl9r** [comment]
@MSFTMan please enhance the documentation with the information you wrote here, I was trying for a while to get this running. If it would be mentioned in the documentation it would be clear
