### ISSUE TITLE
Error while adding Recurence activity in MS Flow

### ISSUE THREAD

**Issue by melzoghbi** [MicrosoftDocs/flow-docs#29]
Hi, I am trying to add Recurrence activity in MS Flow and i am getting the following error: 

"The request content was invalid and could not be deserialized: 'Could not find member 'recurrence' on object of type 'FlowTemplateAction'. Path 'properties.definition.actions.Recurrence.recurrence', line 1, position 205.'."

![image](https://user-images.githubusercontent.com/11993393/46768256-5e11f600-cc9c-11e8-91a7-9f65b83c1efc.png)

any solution for this? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba2e127-56bc-5910-3af6-30030cf58c1f
* Version Independent ID: c8fea93d-3d8d-bf8e-af7d-ae853a936843
* Content: [Run flows on a schedule - Microsoft Flow](https://docs.microsoft.com/en-us/flow/run-scheduled-tasks)
* Content Source: [flow-docs/run-scheduled-tasks.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/run-scheduled-tasks.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@melzoghbi Thanks for reporting this issue. We are not able to reproduce it. Please let us know if you are still seeing it.
Thanks.
