### ISSUE TITLE
Submit Template

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/flow-docs#35]
the submit template is no longer in the list of options under the ellipsis as specified in #2 above

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf8d0d2-3a6f-c3f1-494d-b0ea73c22f9b
* Version Independent ID: 41bc35b2-5a4d-7406-1ae7-27b292033fcd
* Content: [Submit a flow template - Microsoft Flow](https://docs.microsoft.com/en-us/flow/publish-a-template)
* Content Source: [flow-docs/publish-a-template.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/publish-a-template.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by MSFTMan** [comment]
@JerryCRMI Thanks for bringing this item to our attention. It's now fixed: https://docs.microsoft.com/en-us/flow/publish-a-template.
