### ISSUE TITLE
Syntax of special characters

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/flow-docs#36]
Is the syntax correct as using multiple ticks ` in markdown typically causes Flow to print the multiple ticks out? (Which is normal markdown behavior)

Should the syntax be:

`\\` for backslash

`\`\` for backtick

`\_` for underscore

`\{` for curly left brace

`\}` for curly right brace

`\[` for square left bracket

`\]` for square right bracket

`\(` for round left bracket

`\)` for round right bracket

`\#` for hash (see note)

`\+` for plus sign

`\-` for minus sign

`\.` for dot

`\!` for exclamation mark

Note but if your hash appears on the same line as an h1/h2/h3 which themselves start with #, ##, or ### then you need extra escaping for the inline #. In this case, add another # at the end of the line to trick the markdown compiler into closing matching hashes

Also in Markdown, a word or string which begins and ends with the under score `_` will appear _emphasized_. e.g. _Flow Rocks_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Microsoft Flow approvals - Microsoft Flow](https://docs.microsoft.com/en-us/flow/approvals-markdown-support)
* Content Source: [flow-docs/approvals-markdown-support.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/approvals-markdown-support.md)
* Service: **flow**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by MSFTMan** [comment]
@buildbod thanks for reporting this issue. We will investigate it.

**Comment by MSFTMan** [comment]
@buildbod Thanks for your feedback on Microsoft Flow. This issue is being tracked in this item: https://github.com/MicrosoftDocs/flow-docs/issues/99, so I'll close this one. Thank you. -Deon
