### ISSUE TITLE
Can the licencing requirements be added to the Prerequisites

### ISSUE THREAD

**Issue by StevenReid** [MicrosoftDocs/flow-docs#40]
It would be good if details of the Flow Plan that is required for this to work can be added to the Prereqs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f86061a-70b6-f9d0-4450-158876f2cd4d
* Version Independent ID: ee2fde39-1f02-6a2b-ca91-5caba0d1694a
* Content: [Create a modern approval workflow with multiple approvers - Microsoft Flow](https://docs.microsoft.com/en-us/flow/sequential-modern-approvals)
* Content Source: [flow-docs/sequential-modern-approvals.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/sequential-modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@StevenReid Thanks for using Microsoft Flow and for your suggestion. The only prerequisites for Approvals to run are listed in the doc. No special pricing plan is needed. Please let me know if you have any other questions.
