### ISSUE TITLE
Email address requirement to use Flow

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/flow-docs#42]
This requirement appears to be only for when the user is using their personal account, e.g. live.com, outlook.com, etc. However, if the user has a work/school account as part of O365, they don't require an email address. All they would need is to be licensed with Flow. We should update the below Q&A pair to clarify that since right now it implies that an email address is required and that's not always the case. 

What do I need to use Microsoft Flow?
To use Microsoft Flow, all you need is a web browser and an email address. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee8a6fc-8a07-bcf7-412f-21344c46f4c6
* Version Independent ID: 3289c7dd-3a4a-0d96-0e4c-e08689ab2c2d
* Content: [Frequently asked questions - Microsoft Flow](https://docs.microsoft.com/en-us/flow/frequently-asked-questions)
* Content Source: [flow-docs/frequently-asked-questions.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/frequently-asked-questions.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@soyalejolopez Thanks for your feedback. In order to use Microsoft Flow to create flows, you need to sign into Microsoft Flow. If you have a work/school account, you would sign in with your work or school email address. Thanks!
