### ISSUE TITLE
Incorrectly meta data tagged

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/flow-docs#43]
This page is tagged as follows: https://github.com/MicrosoftDocs/flow-docs-pr/blob/b69a63c4e8c2d85cb633ef773acfcccf109650a5/flow-docs/best-practices-workflow-processes.md

Which when you google it using the search term microsoft flow best practices - https://www.google.com/search?q=microsoft+flow+best+practices&oq=microsoft+flow+best+pr&aqs=chrome.0.35i39j69i57.3711j1j4&sourceid=chrome&ie=UTF-8

It comes up at the top of the list.

However, this article is not about best practices for Flow It is about Dynamics 365 Traditional Workflow. Please fix the tagging.

Jerry Weinstock
Business Applications MVP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dab83c1-c2d6-aec4-ae91-d312f8128eac
* Version Independent ID: d296b877-156d-4a3e-4199-12bcfb9e92bf
* Content: [Best practices for workflow processes in PowerApps - Microsoft Flow](https://docs.microsoft.com/en-us/flow/best-practices-workflow-processes#feedback)
* Content Source: [flow-docs/best-practices-workflow-processes.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/best-practices-workflow-processes.md)
* Service: **crm-online**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by MSFTMan** [comment]
@JerryCRMI Thanks for reporting this. I'll look into it.

**Comment by MSFTMan** [comment]
@JerryCRMI Thanks for your feedback, I've removed the reference to PowerApps from the title. Microsoft Flow and Workflows are now part of the overall workflows strategy.
