### ISSUE TITLE
when a new email arrives action subject filter "case insensitive"

### ISSUE THREAD

**Issue by arosa81** [MicrosoftDocs/flow-docs#60]
This would be more useful it wasn't case sensitive

**Comment by MSFTMan** [comment]
@arosa81 Thanks for reporting this issue. So I can help you more, please let me know which service this issue is for.

**Comment by MSFTMan** [comment]
@arosa81 Thanks again for your feedback. I've tested the **When a new email arrives** action in Microsoft Flow, and confirmed that it is case insensitive. Please let us know exactly what subject you're using, and the results, if you are still seeing this issue. I'll close this issue for now. Thanks!
