### ISSUE TITLE
Input Field Length

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/flow-docs#82]
There is no specifications listed for the maximum length of the allowable number of characters for the input field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287efcc3-cbe2-0c93-751b-1cda4a890d47
* Version Independent ID: d90d34da-4a0f-4fe1-ff0f-61a8c815520a
* Content: [Learn how to automate repetitive tasks with button flows that take user input - Microsoft Flow](https://docs.microsoft.com/en-us/flow/button-flow-with-user-input-tokens)
* Content Source: [flow-docs/button-flow-with-user-input-tokens.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/button-flow-with-user-input-tokens.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
Hi @JerryCRMI Thanks for using Microsoft Flow. I'll look into this. - Deon

**Comment by JerryCRMI** [comment]
Hi MSFTMan, what I learned is that there is no maximum length limitation, only a package size. This is a little disconcerting as then there is no guidance in terms of how to set the field size of the target field.
Hope you come up with some better guidance.

**Comment by MSFTMan** [comment]
> Hi MSFTMan, what I learned is that there is no maximum length limitation, only a package size. This is a little disconcerting as then there is no guidance in terms of how to set the field size of the target field.
> Hope you come up with some better guidance.

Thanks for the additional info. I'll pass it on to the team.
