### ISSUE TITLE
Steps to add service account 

### ISSUE THREAD

**Issue by NandaDuddala** [MicrosoftDocs/flow-docs#83]
The above documentation says how to use their personal inbox, It will be really helpful if the documentation provides the steps on how to add the connection of share account / service account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38b2975-5eb6-1aa4-c1fd-d0f033ace5ca
* Version Independent ID: 85899731-9939-a779-29c4-4da652667b74
* Content: [Run flows based on email properties - Microsoft Flow](https://docs.microsoft.com/en-us/flow/email-triggers)
* Content Source: [flow-docs/email-triggers.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/email-triggers.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@NandaDuddala Thanks for your feedback. We'll look into creating a new doc for this.
