### ISSUE TITLE
Minor Code Fixes

### ISSUE THREAD

**Issue by parthpnp** [MicrosoftDocs/flow-docs#84]
There are few fixes require in this sample code.
1. Code line
`hostName:'https:/flow.microsoft.com'`
should be
`hostName:'https://flow.microsoft.com'`

2.Code line
`container: 'flowDiv'`
should have ',' preceding statment
`container: 'flowDiv',`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac3ad92-eb8f-554a-5de3-14c430e594aa
* Version Independent ID: fab1ceb3-5110-4452-0a0d-99346cc31230
* Content: [Integrate Microsoft Flow with websites and apps - Microsoft Flow](https://docs.microsoft.com/en-us/flow/developer/embed-flow-dev)
* Content Source: [flow-docs/developer/embed-flow-dev.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/developer/embed-flow-dev.md)
* Service: **flow**
* GitHub Login: @bbarath
* Microsoft Alias: **barathb**

**Comment by MSFTMan** [comment]
@parthpnp Thanks for using Microsoft Flow. I've fixed this issue.
