### ISSUE TITLE
More explanation needed for Flow Frequency

### ISSUE THREAD

**Issue by nicojdejong** [MicrosoftDocs/flow-docs#85]
For the flow frequency the documentation is not clear. If I user a manual trigger like HTTP Request trigger, can I fire it off as many runs as the pricing tier allows me? Or will there be a delay of 15min between the actual running of a flow when the flow is kicked off by manual trigger like the HTTP request? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1947fd4e-170f-6392-e309-5fd05082ffb8
* Version Independent ID: 79ccd9e1-0998-bc4e-004c-ffbe57291196
* Content: [Billing and metering questions - Microsoft Flow](https://docs.microsoft.com/en-us/flow/billing-questions#what-happens-if-i-try-to-execute-runs-too-frequently)
* Content Source: [flow-docs/billing-questions.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/billing-questions.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@nicojdejong You can fire it as many times as the pricing tier allows. Thanks for using Microsoft Flow.

-Deon
