### ISSUE TITLE
Question on instructions

### ISSUE THREAD

**Issue by cztop54** [MicrosoftDocs/flow-docs#87]
I am using this tutorial.  However, my comments are not updating in my list.  Am I overlooking something. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0b55bf7-5493-bcb9-8689-8658ead17676
* Version Independent ID: 34d682d0-2283-3b1a-2453-6d7dbc26e5a8
* Content: [Create a parallel modern approval workflow - Microsoft Flow](https://docs.microsoft.com/en-us/flow/parallel-modern-approvals)
* Content Source: [flow-docs/parallel-modern-approvals.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/parallel-modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@cztop54 Thanks for using Microsoft Flow. Are there any errors from your run of the flow? Try using the Flow checker.

**Comment by MSFTMan** [comment]
@cztop54 We haven't heard back from you, so we're closing this issue. Kindly let us know if you need further assistance.
