### ISSUE TITLE
Is this list up to date?

### ISSUE THREAD

**Issue by ollij** [MicrosoftDocs/flow-docs#88]
A customer of mine states that European region Flow service is making calls from IP Addresses 40.68.209.23 and 40.68.222.65 which are not on the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Microsoft Flow](https://docs.microsoft.com/en-us/flow/limits-and-config#ip-address-configuration)
* Content Source: [flow-docs/limits-and-config.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
Hello @ollij we are looking into this issue. Thanks for your patience.

**Comment by MSFTMan** [comment]
@ollij These IP addresses are legitimate. You can follow the link to the logic apps IP addresses to see the full list of IP address from which Microsoft Flow makes calls: https://docs.microsoft.com/azure/logic-apps/logic-apps-limits-and-config#configuration-ip-addresses
