### ISSUE TITLE
Note execution context

### ISSUE THREAD

**Issue by SolidKnight** [MicrosoftDocs/flow-docs#89]
It should be made more clear whose security context a Team Flow will operate in as many people want to avoid a scenario where they set up a Team Flow that executes using the creator's (or whoever change it last's) security context. The risk of being able to set this up should be clearly pointed out in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to add other owners to a flow and create team flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-team-flows)
* Content Source: [flow-docs/create-team-flows.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@SolidKnight Thanks for your feedback. We'll improve the documentation on this.
