### ISSUE TITLE
Please use this improved documentation for Recurrence

### ISSUE THREAD

**Issue by John-C-Sinclair** [MicrosoftDocs/flow-docs#90]
There are some important facts missing from this official documentation.
1. If you do not specify a Start time, the flow will trigger immediately, which you probably don't want.
2. You should set the Time zone, otherwise Flow will use the default Time zone of UTC.
3. Provide a Start time in this ISO format:
    YYYY-MM-DDThh:mm:ss if you select a time zone
        -or-
    YYYY-MM-DDThh:mm:ssZ if you don't select a time zone

Please improve this documentation by incorporating all the information at
    https://docs.microsoft.com/en-us/azure/connectors/connectors-native-recurrence
which provides much better documentation for the Recurrence 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba2e127-56bc-5910-3af6-30030cf58c1f
* Version Independent ID: c8fea93d-3d8d-bf8e-af7d-ae853a936843
* Content: [Run flows on a schedule - Microsoft Flow](https://docs.microsoft.com/en-us/flow/run-scheduled-tasks)
* Content Source: [flow-docs/run-scheduled-tasks.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/run-scheduled-tasks.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@John-C-Sinclair Thanks for your feedback. I've added a Learn more section, and link to the document that you referenced. We'll also overhaul this document.

**Comment by John-C-Sinclair** [comment]
Thank you Deon. I have checked https://docs.microsoft.com/en-us/flow/run-scheduled-tasks and the additions haven't been published yet. I'm not familiar with the github repository system, how long will it take before the changes are visible?
