### ISSUE TITLE
ttps://<dynamic app url>/api/data/v9.1/importjobs(00000000-0000-0000-0000-000000000006)

### ISSUE THREAD

**Issue by dpakgithub82** [MicrosoftDocs/flow-docs#91]
importjobs(00000000-0000-0000-0000-000000000006) is this the correct way of giving the Guid for tracking the deployment Progress.
https://&lt;dynamic app url&gt;/api/data/v9.1/importjobs(5092c4e7-7098-43ab-bd55-d8dcbb8b5f03).the Postman responded with coudnt get any response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eecc2503-eee7-8779-2445-d6cd6968a0bd
* Version Independent ID: 532be787-8be9-c9b5-37a2-88841c5b8118
* Content: [Microsoft Flow Web API - Microsoft Flow](https://docs.microsoft.com/en-us/flow/web-api)
* Content Source: [flow-docs/web-api.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/web-api.md)
* GitHub Login: @stepsic-microsoft-com

**Comment by dpakgithub82** [comment]
Poor documentation.

**Comment by KumarVivek** [comment]
@MSFTMan Can you pls look at this issue.

**Comment by MSFTMan** [comment]
@dpakgithub82 Thanks for using Microsoft Flow. This is the correct way. Please let us know if you are still seeing a problem.

**Comment by MSFTMan** [comment]
@dpakgithub82 We haven't heard back from you so we are closing this issue. Please let us know if you need any other assistance.
