### ISSUE TITLE
How do i create a connection using APIs?

### ISSUE THREAD

**Issue by NewJ123** [MicrosoftDocs/flow-docs#93]
Is there any way i can create a connection (or get connection ids) to programatically create/import FLOWs? In my scenario i want to avoid manual steps to get connection name/Ids, and was hoping there is an end point i can hit to create/get connection details?

**Comment by MSFTMan** [comment]
Hello @NewJ123 Thanks for using Microsoft Flow. You can use webapi to manage/create flows. Please take a look at this doc: https://docs.microsoft.com/flow/web-api

**Comment by NewJ123** [comment]
My question is about connections in FLOW APIs

**Comment by NewJ123** [comment]
I would expect atleast you read and Understand the question before simply closing it with a general comment
