### ISSUE TITLE
How to get the Sales manager and HR's email?

### ISSUE THREAD

**Issue by cocohkp** [MicrosoftDocs/flow-docs#94]
Hi,
Is the email hard coded or selected as a token from the search box?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0b55bf7-5493-bcb9-8689-8658ead17676
* Version Independent ID: 34d682d0-2283-3b1a-2453-6d7dbc26e5a8
* Content: [Create a parallel modern approval workflow - Microsoft Flow](https://docs.microsoft.com/en-us/flow/parallel-modern-approvals)
* Content Source: [flow-docs/parallel-modern-approvals.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/parallel-modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@cocohkp  When you are designing your flow, if you use the Get Manager action, then you can select the email address from the list of tokens. Alternatively, you can hard code the email addresses. Thanks for using Microsoft Flow.
