### ISSUE TITLE
Advanced Mode

### ISSUE THREAD

**Issue by KingDrewcifer** [MicrosoftDocs/flow-docs#96]
Currently it seems that the advanced mode option is missing from Conditions in Flow. I love the nesting that was added but I still have a need to use advanced conditions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6af5f3e7-4734-5813-0e3d-dada381fec0b
* Version Independent ID: 393c8bdd-da49-d6cd-f97a-94283f55c0a2
* Content: [Add a condition to a flow - Microsoft Flow](https://docs.microsoft.com/en-us/flow/add-condition)
* Content Source: [flow-docs/add-condition.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/add-condition.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by KingDrewcifer** [comment]
Update the option still doesn't exist but I found ways to achieve what I needed with other enhancements in the condition. And its easier :) Great job!

**Comment by Sburi** [comment]
This option needs to be re-enabled.

**Comment by MSFTMan** [comment]
@KingDrewcifer Thanks for sharing your feedback on Microsoft Flow. I'm sharing this feedback with the product team for consideration. Closing this issue. Thanks!

**Comment by xyh1** [comment]
please re-open, the new condition workflow removed this advanced feature
