### ISSUE TITLE
How do you create a service connection not based on my own email?

### ISSUE THREAD

**Issue by amrock-my** [MicrosoftDocs/flow-docs#97]
I created a flow which utilizes Office 365 Outlook to send an email. Our company uses our full names for our email addresses, so my service connection is my email address, even though the task allows me to change the from email to one we use for our distro.

When I try to add another owner to the flow I get a warning that the other owner will be able to have access to a lot of stuff on my service connection:

Owners with access to this connection can:
Read your user profile
Read, update, and delete your mails
Send mail as signed in user (you)
Create, read, update, and delete events
Create, read, update, and delete contacts

I don't want them to have this access on my email, but rather on the AD group that the email is being sent from. Can I do this somehow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to add other owners to a flow and create team flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-team-flows)
* Content Source: [flow-docs/create-team-flows.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@amrock-my Thank you for your request to enhance the documentation. We’ve recorded your request, and we’ll consider it for a future update to the documentation.
Closing the issue.
