### ISSUE TITLE
Too little documentation on connections

### ISSUE THREAD

**Issue by CodingSinceThe80s** [MicrosoftDocs/flow-docs#98]
Hi guys, as much as I appreciate this awesome tool, I am still baffled by the very scarce documentation on how exactly Flow connections work. I am getting regular prompts to update connections and this is just a no-go in production environments. There are lots of community posts out there with questions regarding connections that just "automagically" expire and no one really has a clear idea on how to handle this. What is worse - Microsofts own posts cite the typical "Just click on verify connection". Is it really so difficult to realize that NO ONE wants to do this in production scenarios? Please update the documentation and give us the down-and-dirty on how exactly these connections work, we can handle it :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d04539c-cf39-3ab2-7ee2-5141e6a5bf89
* Version Independent ID: 81a19210-725f-17a7-238e-1ff3ffe14d23
* Content: [Troubleshooting a flow - Microsoft Flow](https://docs.microsoft.com/en-us/flow/fix-flow-failures)
* Content Source: [flow-docs/fix-flow-failures.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/fix-flow-failures.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@CodingSinceThe80s Thanks for your feedback. This issue has been fixed so you should no longer receive these prompts. Thanks!
